export const SERVER_URL = 'https://www.healage.org/api';
export const PATIENT_ID_FILENAME = 'patientId.cbor';
export const PRESCRIPTIONS_FILENAME = 'prescriptions.cbor';
export const REMINDERS_FILENAME = 'reminders.cbor';
export const DELETION_THRESHOLD = 10 * 1000; // 2 hours
export const DEFERRAL_THRESHOLD = 3; // Defer a max of 3 times
export const CREATION_THRESHOLD = 1 * 60 * 1000; // 1 minute
export const UPDATED_CONFIRMATION_TIMEOUT = 3 * 1000; // 3 seconds
export const NOTIFICATION_INTERVAL = 15 * 1000; // 15 seconds
export const UPDATE_INTERVAL = 30 * 60 * 1000; // 30 minutes
export const POKE_INTERVAL = 15 * 60 * 1000; // 15 minutes
